petstagram/common/urls.py
from django.urls import path, include
from petstagram.common.views import home_page, like_functionality, copy_link_to_clipboard, add_comment

urlpatterns = [
    path('', home_page, name='home'),
    path('like/<int:photo_id>/', like_functionality, name='like'),
    path('share/<int:photo_id>/', copy_link_to_clipboard, name='share'),
    path('comment/<int:photo_id>', add_comment, name='add_comment')
]

petstagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('petstagram.common.urls')),
                  path('accounts/', include('petstagram.accounts.urls')),
                  path('pets/', include('petstagram.pets.urls')),
                  path('photos/', include('petstagram.photos.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petstagram/common/models.py
from django.db import models
from petstagram.photos.models import Photo


class Comment(models.Model):
    comment_text = models.TextField(max_length=300)
    date_time_publication = models.DateTimeField(auto_now_add=True)
    to_photo = models.ForeignKey(Photo, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date_time_publication']


class Like(models.Model):
    to_photo = models.ForeignKey(Photo, on_delete=models.CASCADE)

petstagram/common/forms.py
from django import forms

from petstagram.common.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']

        widgets = {
            'comment_text': forms.Textarea(attrs={'placeholder': 'Add comment...'})
        }


class SearchForm(forms.Form):
    pet_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Search by pet name...'
            }
        )
    )

petstagram/common/views.py
from django.shortcuts import render, redirect, resolve_url
from pyperclip import copy

from petstagram.common.forms import CommentForm, SearchForm
from petstagram.common.models import Like, Comment
from petstagram.photos.models import Photo


def home_page(request):
    all_photos = Photo.objects.all()
    comment_form = CommentForm()
    search_form = SearchForm()

    if request.method == 'POST':
        search_form = SearchForm(request.POST)
        if search_form.is_valid():
            all_photos = all_photos.filter(tagged_pets__name__icontains=search_form.cleaned_data['pet_name'])

    context = {
        'all_photos': all_photos,
        'comment_form': comment_form,
        'search_form': search_form
    }

    return render(request, template_name='common/home-page.html', context=context)


def like_functionality(request, photo_id):
    photo = Photo.objects.get(id=photo_id)
    liked_object = Like.objects.filter(to_photo_id=photo_id).first()

    if liked_object:
        liked_object.delete()
    else:
        like = Like(to_photo=photo)
        like.save()

    return redirect(request.META['HTTP_REFERER'] + f'#{photo_id}')


def copy_link_to_clipboard(request, photo_id):
    copy(request.META['HTTP_HOST'] + resolve_url('photo_details', photo_id))

    return redirect(request.META['HTTP_REFERER'] + f'#{photo_id}')


def add_comment(request, photo_id):
    if request.method == 'POST':
        photo = Photo.objects.get(id=photo_id)
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.to_photo = photo
            comment.save()

            return redirect(request.META['HTTP_REFERER'] + f'#{photo_id}')

petstagram/common/templates/common/home-page.html
{% extends 'base.html' %}

{% block content %}

    <!-- Starts Main Section -->
    <main>
        <div class="container">
            <div class="col-9">

                <!-- Start Searchbar Form -->
                <form class="searchbar" method="post">
                    {% csrf_token %}
                    {{ search_form }}
                    <button>
                        <img src="/static_petstagram/images/search.png" height="18" alt="img2">
                    </button>
                </form>
                <!-- End Searchbar Form -->
                {% for photo in all_photos %}
                    <!-- Start Pet Photos Post Section -->
                    <!-- Start First Pet Photo Post -->
                    <div class="card">
                        <!-- Start User Details and Image Location -->
                        <div class="top">
                            <div class="userDetails">
                                <!-- Link to User Profile Page -->
                                <a href="#">
                                    <div class="profilepic">
                                        <div class="profile_img">
                                            <div class="image">
                                                <img src="/static_petstagram/images/person.png" alt="img8">
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <h3>
                                    <!-- Link to User Profile Page -->
                                    <a href="#">
                                        <!-- if user has first name and last name -->
                                        Diyan Kalaydzhiev
                                        <!-- else -->
                                        <!-- show user username -->
                                    </a>
                                    <br>
                                    <!-- if the photo has location -->
                                    {% if photo.location %}
                                        <span>{{ photo.location }}</span>
                                    {% endif %}
                                </h3>
                            </div>
                        </div>
                        <!-- End User Details and Image Location -->
                        {% for pet in photo.tagged_pets.all %}
                            <!-- Start Pet Photo -->
                            <div class="imgBx" id="place the id of the photo here">
                                <img src="{{ pet.personal_pet_photo }}" alt="post" class="cover">
                            </div>
                            <!-- End Pet Photo -->
                        {% endfor %}

                        <!-- Start Like and Share Buttons -->
                        <div class="bottom">
                            <div class="actionBtns">
                                <div class="left">
                                    <!-- Start Like Button -->
                                    <span class="heart">
									<a href="{% url 'like' photo.id %}">
										<!-- if user has liked the photo -->
                                        {% if photo.like_set.all %}
                                            <svg style="color: red"
                                                 xmlns="http://www.w3.org/2000/svg"
                                                 width="24"
                                                 height="24"
                                                 fill="currentColor"
                                                 class="bi bi-heart-fill"
                                                 viewBox="0 0 16 16">
                                            <!-- Coordinate path -->
                                            <path fill-rule="evenodd"
                                                  d="M8 1.314C12.438-3.248 23.534 4.735
                                                  8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                                  fill="red">

                                            </path>
                                        </svg>
                                            <!-- else -->
                                        {% else %}
                                            <svg aria-label="Like"
                                                 color="#262626"
                                                 fill="#262626"
                                                 height="24"
                                                 role="img"
                                                 viewBox="0 0 48 48"
                                                 width="24">
                                        {% endif %}
                                        <!-- Coordinate path -->
                                        <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4
                                                    11.5 0 6.8-5.9 11-11.5 16S25 41.3 24
                                                    41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3
                                                    11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3
                                                    1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9
                                                    1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9
                                                    1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1
                                                    0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3
                                                    1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3
                                                    1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2
                                                    7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6
                                                    48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                                        </path>
                                        </svg>
								</a>
								</span>
                                    <!-- End Like Button -->

                                    <!-- Start Share Button -->
                                    <a href="{% url 'share' photo.id %}">
                                        <svg aria-label="Share Post" class="_8-yf5 " color="#262626" fill="#262626"
                                             height="24" role="img" viewBox="0 0 48 48" width="24">
                                            <path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3
										3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6
										1 1.2 1.1h.2c.5 0 1-.3
										1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2
										6.1h35.5L18 18.7 5.2 6.1zm18.7
										33.6l-4.4-18.4L42.4 8.6 23.9 39.7z">
                                            </path>
                                        </svg>
                                    </a>
                                    <!-- End Share Button -->

                                </div>
                            </div>
                            <!-- End Like and Share Buttons -->

                            <!-- Number of Likes per Photo -->
                            <p class="likes">{{ photo.like_set.count }}</p>


                            <!-- Start Tagged Pets -->
                            <!-- Link to First Tagged Pet Details Page-->
                            {% for pet in photo.tagged_pets.all %}
                                <a href="#">
                                    <p class="message">
                                        <b>{{ pet.name }}</b>
                                    </p>
                                </a>
                            {% endfor %}

                            <!-- Link to Second Tagged Pet Details Page-->
                            <a href="#">
                                <p class="message">
                                    <b>{{ photo.description }}</b>
                                </p>
                            </a>
                            <!-- End Tagged Pets -->

                            <!-- Link to Photo Details Page -->
                            <a href="{% url 'photo_details' photo.id %}">
                                <h4 class="details">See details</h4>
                            </a>

                            <!-- Date of Publication -->
                            <h5 class="postTime">{{ photo.date_of_publication }}</h5>

                            <!-- Start Add Comments Section -->
                            <div class="addComments">
                                <div class="reaction">
                                    <h3>
                                        <i class="far fa-smile"></i>
                                    </h3>
                                </div>
                                <!-- Start Add Comments Form -->
                                <form method="post" action="{% url 'add_comment' photo.id %}">
                                    {% csrf_token %}
                                    {{ comment_form }}
                                    <button type="submit">Post</button>
                                </form>
                                <!-- End Add Comments Form -->

                            </div>
                            <!-- End Add Comments Section -->

                        </div>
                    </div>
                    <!-- End First Pet Photo Post -->
                {% endfor %}

            </div>
        </div>
    </main>
    <!-- End Main Section -->

{% endblock %}